name: Lint and Format

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main

env:
  pythonVersion: 3.12

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.pythonVersion }}

      - name: Install dependencies
        run: |
            pip install flake8 black
            apt install flake8
            apt install black
              
      - name: Run flake8
        run: flake8 .

      - name: Run black check
        run: black --check .
