name: Test Suite

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # TODO: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install MetaCall (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

      - name: Install MetaCall (Windows)
        if: matrix.os == 'windows-latest'
        run: powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/metacall/install/master/install.ps1')))"

      # TODO:
      # - name: Install MetaCall (MacOS)
      #   if: matrix.os == 'macos-latest'
      #   run: curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: |
          for test in ./suites/*.yaml; do
            echo "Running $test"
            python3 ./testing.py -f $test -V
          done
