name: MetaCall Examples CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        env: [cli, faas]
        nodeVersion: [14] # Only for environments requiring Node.js
        pythonVersion: [3.12] # Only for environments requiring Python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Install MetaCall (CLI only)
        if: matrix.env == 'cli' && matrix.os == 'ubuntu-latest'
        run: |
            sudo apt update
            curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh
            metacall
        shell: bash

      - name: Install MetaCall (CLI only)
        if: matrix.env == 'cli' && matrix.os == 'windows-latest'
        run: |
          powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/metacall/install/master/install.ps1')))"
          echo C:\Users\runneradmin\AppData\Local\MetaCall >> $env:GITHUB_PATH
          metacall.bat
        shell: powershell

      - name: Set up Node.js
        if: matrix.env == 'faas'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}

      - name: Install MetaCall Deploy (FaaS only)
        if: matrix.env == 'faas'
        run: |
          npm i -g @metacall/deploy
          metacall-deploy --version 

          npm i -g @metacall/faas
          metacall-faas --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run FaaS in Background (FaaS only)
        if: matrix.env == 'faas'
        run: |
          metacall-faas &
        shell: bash

      - name: Run Test Suits
        run: |
          find test-suites -type f -name "*.yaml" -exec python ./testing.py -f {} -V -e ${{ matrix.env }} \;
        shell: bash
